require_relative '../pages/page'

# Configuration Class Page that is generated by configuration
class ConfigurationPage < Page
  include ConfigurationModule

  def initialize(browser, name)
    raise IOError.new "The file #{name}.yml was not found in the page configurations folder." unless  page_file_exists? name
    @browser = browser
    add_controls(name)
    super browser
  end
end
