source 'https://rubygems.org'
ruby '2.5.5'

gem 'appium_lib'
gem 'colorize'
gem 'csv'
gem 'cucumber', '3.1.2'
gem 'fileutils'
gem 'httpi'
gem 'json'
gem 'jwt'
gem 'mongo'
gem 'mysql2'
gem 'net-ssh'
gem 'nokogiri'
gem 'nori'
gem 'os'
gem 'mail'
gem 'parallel_tests'
gem 'pg'
gem 'pry'
gem 'report_builder'
gem 'rspec'
gem 'ruby-oci8'
gem 'savon'
gem 'selenium-webdriver'
gem 'roo', '~> 2.8', '>= 2.8.3'
gem 'roo-xls'
gem 'tiny_tds'
gem 'watir'
gem 'watir-screenshot-stitch'
gem 'webdrivers'
